deconflict pc macro with boost
Previously I used `pc` as a macro for the constant of parsecs in
terms of centimeters. Unfortunately boost now uses `pc` in one of its
files, which caused gcc to break.

For now I've simply renamed `pc` to `pc_unit`. I haven't changed any
other unit macros in `constants.H`; ideally I would add something like
a prefix/suffix to make sure they would never reasonably conflict.

Error message:

~~~~
In file included from cooling.cxx:21:
In file included from /usr/local/include/boost/filesystem.hpp:16:
In file included from /usr/local/include/boost/filesystem/path.hpp:25:
In file included from /usr/local/include/boost/filesystem/path_traits.hpp:23:
/usr/local/include/boost/system/error_code.hpp:235:70: error: expected ')'
        explicit std_category( boost::system::error_category const * pc ): pc_( pc )
                                                                     ^
./constants.H:13:13: note: expanded from macro 'pc'
            ^
/usr/local/include/boost/system/error_code.hpp:235:30: note: to match this '('
        explicit std_category( boost::system::error_category const * pc ): pc_( pc )
                             ^
/usr/local/include/boost/system/error_code.hpp:235:76: error: cannot initialize a member subobject of type
      'const boost::system::error_category *' with an rvalue of type 'double'
        explicit std_category( boost::system::error_category const * pc ): pc_( pc )
                                                                           ^    ~~

~~~~